[package]
name = "vis-cli"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
toml = "1.1.2"
vis-analyzer = { path = "../vis-analyzer" }
vis-diagnostics = { path = "../vis-diagnostics" }
vis-parser = { path = "../vis-parser" }
vis-rules = { path = "../vis-rules" }
walkdir = "2.5.0"
