[package]
name = "vis-rules"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
vis-diagnostics = { path = "../vis-diagnostics" }
vis-ir = { path = "../vis-ir" }

[dev-dependencies]
vis-analyzer = { path = "../vis-analyzer" }
vis-parser = { path = "../vis-parser" }
